[tools]
flutter = "3.41"
java = "25" # used for openapi gen
'npm:@openapitools/openapi-generator-cli' = "latest"
'npm:firebase-tools' = "latest"

[tasks.analyze]
description = "Runs flutters static code analyzer"
run = "flutter analyze"

[tasks.dependencies]
description = "Upgrades Flutter and loads required dependencies."
run = """
  flutter upgrade
  flutter pub upgrade
  flutter pub get
  """

[tasks.generate]
description = "Generates Dart API client from OpenAPI spec."
run = """
      openapi-generator-cli generate \
        -i ../openapi/api.yaml \
        -g dart-dio \
        -o generated_api \
        --additional-properties=pubName=bookclub_api
      sed -i "s/sdk: '>=2.18.0 <4.0.0'/sdk: '>=3.0.0 <4.0.0'/" generated_api/pubspec.yaml
      cd generated_api && dart pub get && dart run build_runner clean && dart run build_runner build
      cd - && flutter pub get
    """


[tasks.test]
description = "Run flutter tests"
depends = ['dependencies', 'analyze', 'generate']
run = "flutter test"

[tasks.start]
description = "Starts the app locally for Chrome"
depends = ['test']
run = "flutter run -d web-server --web-port=8080 --dart-define=API_BASE_URL=$API_BASE_URL --dart-define=GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY"

[tasks.build]
description = "Builds the app for WEB"
depends = ['test']
run = "flutter build web --dart-define=API_BASE_URL=$API_BASE_URL --dart-define=GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY"

[tasks.deploy]
description = "Deploys the WEB app"
depends = ['build']
run = 'firebase deploy --only hosting'
