version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: bookclub-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
