server:
  port: ${PORT:8080}

spring:
  application:
    name: backend
  datasource:
    url:
    username: dev
    password: dev
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when-authorized