# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: jdx/mise-action@v2
        with:
          version: 2024.12.14 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
          working_directory: frontend

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.5

      - name: Install dependencies
        working-directory: frontend
        run: mise run dependencies

      - name: Analyze project source
        working-directory: frontend
        run: mise run analyze

      - name: Run tests
        working-directory: frontend
        run: mise run --skip-deps test
        
      - name: Run build
        working-directory: frontend
        run: mise --skip-deps run build
